name: Enforce Merge Hierarchy

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  validate-merge-source:
    runs-on: ubuntu-latest
    steps:
      - name: Debug PR Info
        run: |
          echo "Base branch: ${{ github.base_ref }}"
          echo "Head branch: ${{ github.head_ref }}"

      - name: Check PR source branch
        run: |
          BASE_BRANCH="${{ github.base_ref }}"  # Target branch
          HEAD_BRANCH="${{ github.head_ref }}"  # Source branch
          
          case "$BASE_BRANCH" in
            "main")
              if [[ "$HEAD_BRANCH" == "development" ]]; then
                exit 0
              else
                exit 1
              fi
              ;;
            "development")
              if [[ "$HEAD_BRANCH" == "staging" || "$HEAD_BRANCH" == "main" ]]; then
                exit 0
              else
                exit 1
              fi
              ;;
            "staging")
                exit 0
              ;;
            *)
             exit 0
              ;;
          esac
